### PR TITLE
Enable multi-arch docker image build

### PR DESCRIPTION
**Pull request by hat3ph**
Hi kopi1984, I notice you public the arm64 docker image for adguard-unbound to docker hub. Do you mind try to enable multi-arch for the docker image too?

### CODE REVIEW

**Comment by Kopi1984** [comment]
> Hi kopi1984, I notice you public the arm64 docker image for adguard-unbound to docker hub. Do you mind try to enable multi-arch for the docker image too?

Hi There,
Sorry for this late reply, kinda busy this season.
Glad to hear from you, I've been reading much your blog. 
I did try your docker file before, but it did not work! I give it another try soon.

**Comment by hat3ph** [comment]
Does it work?

**Comment by Kopi1984** [comment]
> Does it work?

I tried many times but it still did not work. I'm checking a code of building image for multi arch.

**Comment by hat3ph** [comment]
Try out docker buildx

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Pull request merged**
